import { TuitionJob, CreditPackage } from './types';

export const creditPackages: CreditPackage[] = [
  {
    id: 'silver',
    name: 'Silver Package',
    price: 500,
    credits: 3,
    tutorTypes: ['Bangla Medium', 'English Version'],
    salaryRange: '৳2,000 - ৳5,000',
    color: 'bg-gradient-to-br from-gray-100 to-gray-300'
  },
  {
    id: 'gold',
    name: 'Gold Package',
    price: 800,
    credits: 3,
    tutorTypes: ['English Version', 'English Medium'],
    salaryRange: '৳2,000 - ৳12,000',
    color: 'bg-gradient-to-br from-yellow-100 to-yellow-300'
  },
  {
    id: 'diamond',
    name: 'Diamond Package',
    price: 1000,
    credits: 4,
    tutorTypes: ['Premium Tuition'],
    salaryRange: '৳5,000 - ৳40,000+',
    color: 'bg-gradient-to-br from-blue-100 to-blue-300'
  }
];

export const tuitionJobs: TuitionJob[] = [
  {
    id: '1',
    location: 'Dhanmondi, Dhaka',
    studentClass: 'Class 8',
    preferredTutorGender: 'Any',
    salaryRange: '৳3,000/month',
    tutorType: 'Bangla Medium',
    studentGender: 'Female',
    studyCategory: 'All Subjects',
    classLevel: 'Secondary',
    numberOfStudents: 1,
    preferredTime: 'After School',
    daysPerWeek: 3,
    demoClassDate: '2024-03-25',
    clientName: 'Rahman Family',
    clientPhone: '+880 1711-XXXXXX'
  },
  {
    id: '2',
    location: 'Gulshan, Dhaka',
    studentClass: 'Class 10',
    preferredTutorGender: 'Female',
    salaryRange: '৳15,000/month',
    tutorType: 'English Medium',
    studentGender: 'Female',
    studyCategory: 'Science',
    classLevel: 'O Level',
    numberOfStudents: 1,
    preferredTime: 'Evening',
    daysPerWeek: 4,
    demoClassDate: '2024-03-26',
    clientName: 'Ahmed Family',
    clientPhone: '+880 1812-XXXXXX'
  },
  {
    id: '3',
    location: 'Uttara, Dhaka',
    studentClass: 'Class 5',
    preferredTutorGender: 'Male',
    salaryRange: '৳4,000/month',
    tutorType: 'English Version',
    studentGender: 'Male',
    studyCategory: 'All Subjects',
    classLevel: 'Primary',
    numberOfStudents: 1,
    preferredTime: 'Morning',
    daysPerWeek: 3,
    demoClassDate: '2024-03-27',
    clientName: 'Islam Family',
    clientPhone: '+880 1913-XXXXXX'
  },
  {
    id: '4',
    location: 'Banani, Dhaka',
    studentClass: 'Class 12',
    preferredTutorGender: 'Any',
    salaryRange: '৳8,000/month',
    tutorType: 'English Version',
    studentGender: 'Male',
    studyCategory: 'Science',
    classLevel: 'HSC',
    numberOfStudents: 1,
    preferredTime: 'Evening',
    daysPerWeek: 5,
    demoClassDate: '2024-03-28',
    clientName: 'Hossain Family',
    clientPhone: '+880 1614-XXXXXX'
  },
  {
    id: '5',
    location: 'Mirpur, Dhaka',
    studentClass: 'Class 7',
    preferredTutorGender: 'Female',
    salaryRange: '৳3,500/month',
    tutorType: 'Bangla Medium',
    studentGender: 'Female',
    studyCategory: 'All Subjects',
    classLevel: 'Secondary',
    numberOfStudents: 2,
    preferredTime: 'Afternoon',
    daysPerWeek: 3,
    demoClassDate: '2024-03-29',
    clientName: 'Begum Family',
    clientPhone: '+880 1515-XXXXXX'
  },
  {
    id: '6',
    location: 'Mohammadpur, Dhaka',
    studentClass: 'Class 9',
    preferredTutorGender: 'Male',
    salaryRange: '৳6,000/month',
    tutorType: 'English Version',
    studentGender: 'Male',
    studyCategory: 'Science',
    classLevel: 'Secondary',
    numberOfStudents: 1,
    preferredTime: 'Evening',
    daysPerWeek: 4,
    demoClassDate: '2024-03-30',
    clientName: 'Khan Family',
    clientPhone: '+880 1816-XXXXXX'
  },
  {
    id: '7',
    location: 'Bashundhara, Dhaka',
    studentClass: 'A Level',
    preferredTutorGender: 'Any',
    salaryRange: '৳20,000/month',
    tutorType: 'Premium Tuition',
    studentGender: 'Female',
    studyCategory: 'Physics, Chemistry',
    classLevel: 'A Level',
    numberOfStudents: 1,
    preferredTime: 'Flexible',
    daysPerWeek: 3,
    demoClassDate: '2024-03-31',
    clientName: 'Chowdhury Family',
    clientPhone: '+880 1717-XXXXXX'
  },
  {
    id: '8',
    location: 'Baridhara, Dhaka',
    studentClass: 'Class 6',
    preferredTutorGender: 'Female',
    salaryRange: '৳10,000/month',
    tutorType: 'English Medium',
    studentGender: 'Female',
    studyCategory: 'All Subjects',
    classLevel: 'Primary',
    numberOfStudents: 1,
    preferredTime: 'Afternoon',
    daysPerWeek: 5,
    demoClassDate: '2024-04-01',
    clientName: 'Siddique Family',
    clientPhone: '+880 1618-XXXXXX'
  },
  {
    id: '9',
    location: 'Khilgaon, Dhaka',
    studentClass: 'Class 4',
    preferredTutorGender: 'Any',
    salaryRange: '৳4,500/month',
    tutorType: 'Bangla Medium',
    studentGender: 'Male',
    studyCategory: 'All Subjects',
    classLevel: 'Primary',
    numberOfStudents: 1,
    preferredTime: 'Morning',
    daysPerWeek: 3,
    demoClassDate: '2024-04-02',
    clientName: 'Alam Family',
    clientPhone: '+880 1919-XXXXXX'
  }
];